version: '3.8'

services:
  backend:
    # build:
    #   context: ../..
    #   dockerfile: ./docker/Dockerfile_arm64
    #   args:
    #     CACHE_EXCHANGE_RATES_PERIOD: ""
    #     API_V1_READ_METHODS_DISABLED: "false"
    #     DISABLE_WEBAPP: "false"
    #     API_V1_WRITE_METHODS_DISABLED: "false"
    #     CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED: ""
    #     CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
    #     ADMIN_PANEL_ENABLED: "true"
    #     RELEASE_VERSION: 5.2.3
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    pull_policy: always
    # platform: linux/amd64
    restart: always
    stop_grace_period: 5m
    container_name: 'backend'
    environment:
        NETWORK: Cryptonomic0n
        SUBNETWORK: Ethereum
        ETHEREUM_JSONRPC_VARIANT: 'geth'
        ETHEREUM_JSONRPC_HTTP_URL: https://bs-tst:msdhDbr347145234@node.cryptonomicon.space:14438
        ETHEREUM_JSONRPC_TRACE_URL: https://bs-tst:msdhDbr347145234@node.cryptonomicon.space:14438
        DATABASE_URL: postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false
        DISABLE_INDEXER: 'false'
        # FIRST_BLOCK: 13600000
        # TRACE_FIRST_BLOCK: 13600000
        MICROSERVICE_SC_VERIFIER_ENABLED: 'true'
        MICROSERVICE_SC_VERIFIER_URL: http://smart-contract-verifier:8050/
        MICROSERVICE_SC_VERIFIER_TYPE: sc_verifier
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ../envs/common-blockscout.env
    volumes:
      - ./logs/:/app/logs/